name: CI/CD

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  composer:
    name: composer install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      - name: Setup PHP cache
        uses: shivammathur/cache-extensions@v1
        id: php-ext-cache
        with:
          php-version: '8.4'
          extensions: zip
          key: php84-cache
      - name: Cache PHP extensions
        uses: actions/cache@v5
        with:
          path: ${{ steps.php-ext-cache.outputs.dir }}
          key: ${{ steps.php-ext-cache.outputs.key }}
          restore-keys: ${{ steps.php-ext-cache.outputs.key }}
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: zip
          coverage: none
      - name: Cache Composer dependencies
        uses: actions/cache@v5
        id: composer-cache
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress --no-scripts --no-autoloader

      - name: Generate Composer autoloader
        run: composer dump-autoload

  phpcs:
    name: phpcs
    needs: composer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      - name: Setup PHP cache
        uses: shivammathur/cache-extensions@v1
        id: php-ext-cache
        with:
          php-version: '8.4'
          extensions: zip
          key: php84-cache
      - name: Cache PHP extensions
        uses: actions/cache@v5
        with:
          path: ${{ steps.php-ext-cache.outputs.dir }}
          key: ${{ steps.php-ext-cache.outputs.key }}
          restore-keys: ${{ steps.php-ext-cache.outputs.key }}
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: zip
          coverage: none
      - name: Cache Composer dependencies
        uses: actions/cache@v5
        id: composer-cache
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Cache php-cs-fixer cache
        uses: actions/cache@v5
        id: php-cs-fixer-cache
        with:
          path: .php-cs-fixer.cache
          key: ${{ runner.os }}-php-cs-fixer-${{ github.ref }}-${{ hashFiles('.php-cs-fixer.php') }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-php-cs-fixer-${{ github.ref }}-${{ hashFiles('php-cs-fixer.php') }}-
            ${{ runner.os }}-php-cs-fixer-${{ github.ref }}-
            ${{ runner.os }}-php-cs-fixer-
      - name: Validate code style
        run: composer phpcs:ci
        env:
          PHP_CS_FIXER_IGNORE_ENV: 1

  phpstan:
    name: phpstan
    needs: composer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      - name: Setup PHP cache
        uses: shivammathur/cache-extensions@v1
        id: php-ext-cache
        with:
          php-version: '8.4'
          extensions: zip
          key: php84-cache
      - name: Cache PHP extensions
        uses: actions/cache@v5
        with:
          path: ${{ steps.php-ext-cache.outputs.dir }}
          key: ${{ steps.php-ext-cache.outputs.key }}
          restore-keys: ${{ steps.php-ext-cache.outputs.key }}
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: zip
          coverage: none
      - name: Cache Composer dependencies
        uses: actions/cache@v5
        id: composer-cache
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Cache PHPStan cache
        uses: actions/cache@v5
        id: phpstan-cache
        with:
          path: storage/tmp/phpstan
          key: ${{ runner.os }}-phpstan-${{ github.ref }}-${{ hashFiles('phpstan.neon') }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-phpstan-${{ github.ref }}-${{ hashFiles('phpstan.neon') }}-
            ${{ runner.os }}-phpstan-${{ github.ref }}-
            ${{ runner.os }}-phpstan-
      - name: Run PHPStan
        run: |
          cp .env.testing.template .env.testing
          composer phpstan:ci
        env:
          APP_ENV: 'testing'
        timeout-minutes: 15

  test:
    name: tests
    needs: composer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      - name: Setup PHP cache
        uses: shivammathur/cache-extensions@v1
        id: php-ext-cache
        with:
          php-version: '8.4'
          extensions: zip, openssl
          key: php84-cache
      - name: Cache PHP extensions
        uses: actions/cache@v5
        with:
          path: ${{ steps.php-ext-cache.outputs.dir }}
          key: ${{ steps.php-ext-cache.outputs.key }}
          restore-keys: ${{ steps.php-ext-cache.outputs.key }}
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: zip, openssl
          coverage: none
      - name: Cache Composer dependencies
        uses: actions/cache@v5
        id: composer-cache
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Run PHPUnit
        run: |
          cp .env.testing.template .env.testing
          composer test:ci
        env:
          APP_ENV: 'testing'

  security:
    name: security
    needs: composer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      - name: Check for security issues in dependencies
        uses: symfonycorp/security-checker-action@v5

  yarn:
    name: yarn install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      - name: Cache Yarn dependencies
        uses: actions/cache@v5
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Install Yarn dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

  prettier:
    name: prettier
    needs: yarn
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      - name: Cache Yarn dependencies
        uses: actions/cache@v5
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Validate code style
        run: yarn run prettier:ci
